import { expect, test } from "@playwright/test";

test("dragging retains the chosen angle and keyboard inspection remains available", async ({ page }) => {
  await page.goto("/");
  const scene = page.locator(".scape-frame");
  await scene.scrollIntoViewIfNeeded();
  await expect(scene.getByRole("button", { name: "Reset view" })).toBeVisible();
  const svg = scene.getByRole("img");
  const face = scene.locator('.scape-bar[data-tone="history"] polygon').first();
  const initial = await face.getAttribute("points");
  await page.waitForTimeout(300);
  expect(await face.getAttribute("points")).toBe(initial);
  const box = (await svg.boundingBox())!;
  await page.mouse.move(box.x + box.width * 0.45, box.y + box.height * 0.5);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * 0.65, box.y + box.height * 0.55, { steps: 8 });
  await page.mouse.up();
  await expect.poll(() => face.getAttribute("points")).not.toBe(initial);
  const rotated = await face.getAttribute("points");
  await page.waitForTimeout(300);
  expect(await face.getAttribute("points")).toBe(rotated);
  await expect(scene).toHaveAttribute("data-dragging", "false");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await svg.focus();
  await page.keyboard.press("Shift+ArrowLeft");
  await expect.poll(() => face.getAttribute("points")).not.toBe(rotated);
  await page.keyboard.press("End");
  await expect(scene.locator('[aria-live="polite"]')).not.toBeEmpty();
  await expect(page.getByText("A single line", { exact: true })).toHaveCount(0);
  await expect(page.getByText("A line and its range", { exact: true })).toHaveCount(0);
  await expect(page.locator("#compare svg")).toHaveCount(0);
});

test("cursor perspective settles on leave, weeks can be held, and reset restores the scene", async ({ page }) => {
  await page.goto("/");
  const scene = page.locator(".scape-frame");
  const svg = scene.getByRole("img");
  await svg.scrollIntoViewIfNeeded();
  const face = scene.locator('.scape-bar[data-tone="history"] polygon').first();
  const initial = await face.getAttribute("points");
  const box = (await svg.boundingBox())!;
  await page.mouse.move(box.x + box.width * 0.85, box.y + box.height * 0.3);
  await expect.poll(() => face.getAttribute("points")).not.toBe(initial);
  await page.mouse.move(1, 1);
  await expect.poll(() => face.getAttribute("points")).toBe(initial);

  await svg.focus();
  await page.keyboard.press("End");
  await page.keyboard.press("Enter");
  await expect(scene).toHaveAttribute("data-pinned", "true");
  await expect(scene.locator(".scape-readout")).toContainText("Week +8");
  await page.mouse.move(box.x + box.width * 0.25, box.y + box.height * 0.6);
  await expect(scene.locator(".scape-readout")).toContainText("Week +8");
  await scene.getByRole("button", { name: "Release week" }).click();
  await expect(scene).not.toHaveAttribute("data-pinned", "true");
  await scene.getByRole("button", { name: "Reset view" }).click();
  await expect.poll(() => face.getAttribute("points")).toBe(initial);

  await page.emulateMedia({ reducedMotion: "reduce" });
  await svg.scrollIntoViewIfNeeded();
  const reducedBox = (await svg.boundingBox())!;
  await page.mouse.move(reducedBox.x + reducedBox.width * 0.8, reducedBox.y + reducedBox.height * 0.3);
  await page.waitForTimeout(250);
  expect(await face.getAttribute("points")).toBe(initial);
  await scene.locator('.scape-bar[data-tone="future"][data-row="0"][data-step="20"] polygon').first().click();
  await expect(scene).toHaveAttribute("data-pinned", "true");
  await expect(scene.locator(".scape-readout")).toContainText("Week +5");
  await svg.focus();
  await page.keyboard.press("ArrowRight");
  await expect(scene.locator(".scape-readout")).toContainText("Week +6");
});

test("a horizontal touch gesture rotates the scene", async ({ browser }) => {
  const context = await browser.newContext({ hasTouch: true, isMobile: true, viewport: { width: 390, height: 844 } });
  const page = await context.newPage();
  await page.goto("/");
  const svg = page.locator('.scape-frame svg[role="img"]');
  await svg.scrollIntoViewIfNeeded();
  const face = svg.locator('.scape-bar[data-tone="history"] polygon').first();
  const initial = await face.getAttribute("points");
  const box = (await svg.boundingBox())!;
  const session = await context.newCDPSession(page);
  const x = box.x + box.width * 0.4;
  const y = box.y + box.height * 0.5;
  await session.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x, y }] });
  await session.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: x + 70, y }] });
  await session.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  await expect.poll(() => face.getAttribute("points")).not.toBe(initial);
  await expect(page.locator(".scape-frame")).toHaveAttribute("data-dragging", "false");
  await context.close();
});
